module.exports = [
                  {
					 typeTranform:'fromArabicToRomanNumber',
                     equivalence :{
					                 fromArabic:1,
								     toRoman:'I'
							       }
					},
					{
					  typeTranform:'fromArabicToRomanNumber',
					  equivalence :{
						              fromArabic:5,
							   	      toRoman:'V'
							        },
					  lastEquivalence:[{
							            fromArabic:1,
									     toRoman:'I'
					                 }]
					},
					{
					  typeTranform:'fromArabicToRomanNumber',
					  equivalence :{
							         fromArabic:10,
									 toRoman:'X'
									},
					  lastEquivalence:[{
							            fromArabic:1,
									     toRoman:'I'
					                 }]
					},
                   {
					 typeTranform:'fromArabicToRomanNumber',
                     equivalence :{
					                 fromArabic:50,
								     toRoman:'L'
							       },
					  lastEquivalence:[{
							            fromArabic:10,
									     toRoman:'X'
					                 },
					                 {
							            fromArabic:1,
									     toRoman:'1'
					                 }]
					},
					{
					  typeTranform:'fromArabicToRomanNumber',
					  equivalence :{
						              fromArabic:100,
							   	      toRoman:'C'
							        },
					  lastEquivalence:[{
							            fromArabic:10,
									     toRoman:'X'
					                 },
					                 {
							            fromArabic:1,
									     toRoman:'I'
					                 }]

					},
					{
					  typeTranform:'fromArabicToRomanNumber',
					  equivalence :{
							         fromArabic:500,
									 toRoman:'D'
									},
					  lastEquivalence:[{
							            fromArabic:100,
									     toRoman:'C'
					                 },
					                 {
							            fromArabic:10,
									     toRoman:'X'
					                 },
					                 {
							            fromArabic:1,
									     toRoman:'I'					                 	
					                 }]
					},
					{
					  typeTranform:'fromArabicToRomanNumber',
					  equivalence :{
							         fromArabic:1000,
									 toRoman:'M'
									},
					  lastEquivalence:[{
							            fromArabic:100,
									     toRoman:'C'
					                 },
					                 {
							            fromArabic:10,
									     toRoman:'X'
					                 },
					                 {
							            fromArabic:1,
									     toRoman:'I'					                 	
					                 }]
					}
                  ]